// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';

export function GetDirectory(arg1:string):Promise<Array<fs.DirEntry>>;

export function GetFolder(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LiveOutput(arg1:any):Promise<string>;
