// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectory(arg1) {
  return window['go']['api']['App']['GetDirectory'](arg1);
}

export function GetFolder(arg1) {
  return window['go']['api']['App']['GetFolder'](arg1);
}

export function Greet(arg1) {
  return window['go']['api']['App']['Greet'](arg1);
}

export function LiveOutput(arg1) {
  return window['go']['api']['App']['LiveOutput'](arg1);
}
